apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-kubernetes
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: zabbix-kubernetes
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix-kubernetes
    spec:
      containers:
        - name: k8s-zabbix
          # add your
          #image: your-repo.foo.bar:k8s-zabbix:latest
          image: scoopex666/k8s-zabbix:latest
          args: [ "config_default" ]
          # review config_default.py for additionaol configuration values (convert the names to uppercase)
          env:
             # the ingress hostname where you can reach the k8s api
             - name: "K8S_API_HOST"
               value: "http://k8s-api.foo.bar/"
             # if you ignore the advice of the installation instructions to create a ingress with a offical certificate and instead to connect to a controller, you should set this to "False"
             - name: "VERIFY_SSL"
               value: "True"
             # the k8s api token, where you can fetch information from the k8s cluster
             - name: "K8S_API_TOKEN"
               value: "FAKE-4uo7ahn0HaireePhohmieCix5eecoox6luv9ahngaiwieweem1wooxie4ooch1Meingeetai7Esh9toiQuaith1uphae2thoonae9yoo0ye0eiy2Ien2iecaNgiudut3kohjahfeilooShaewoch3ibeezieTas8seijaiwed3ei0ShuGo5nooqua5Yaixieghaihiaquahvae6Oowiqu8Yahko4in6Nievai7rohghohbiThei5gai5Ohqu0bo5ahphah4uuquohfaif6rae0ahCheijeSahkae2Voox8seivo5ohg6niSh3thuk8seemo4Eixir8eb0miejeeSeem3aen5noovohchoop1weikieliith0eaPoJohkee8nou4Voja9eiyoh4oenie3reehohriichool6baegeeghien5uibiemooghoRahshaibea8Foo5zaiT5kood9quae6Naiw4hohvei6fae9goyei4yafeesh8Eiciepha1ahseZ7Eesho3oa0yiicieyaiShoh8eivi7kahv8nae5eivohZ8ierengaepoh1fiezo2Oth1boy6jeichah6eiDeiquun5Ach4chithui2Gei7ohchu1uephekalichahzeigh1ohV9aceyah1phahohsoo6eisieJohw7uk4Zo5Iedai8iW9ut4beePh1bai3Oogh7Aighi6uiPhapoo4loo2eth4el0Ieng7ZeeV0aiXiJaigh5AhlabieBir3Aegoh5aey8coRah2Aehee3shutiej1johy6mieXahxiePe"
             # the zabbix server/proxy where measurements and status information should be delivered
             - name: "ZABBIX_SERVER"
               value: "zabbix.api.foo.bar:10080"
             # the abstract/virtual host which is configured in zabbix to hold and alert k8s zabbix 
             - name: "ZABBIX_HOST"
               value: "k8s-prod-001"
             # Enable the optional management api status submission
             - name: "WEB_API_ENABLE"
               value: "False"
             # The base uri of the anagement api status submission
             - name: "WEB_API_HOST"
               value: "https://example.api.com/api/v1/k8s"
             # The security token for management api status submission
             - name: "WEB_API_TOKEN"
               value: "17812110692887024374221963068327794883098412835131004"
             # The name of the k8s cluster in the management system
             - name: "web_api_cluster"
               value: "k8s-test-cluster"
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "250m"
